{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bitwarden.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: '/'
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
          {{- if .Values.bitwarden.websocket_enabled }}
          - path: '/notifications/hub'
            backend:
              serviceName: {{ $fullName }}
              servicePort: websocket
          - path: '/notifications/hub/negotiate'
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
          {{- end }}
{{- end }}
